version: '3'
services:
  wradlib:
    container_name: 'wradlib-radolan-test'
    image: technologiestiftung/inspect-radolan:test
    # build:
    #   context: '.'
    #   dockerfile: 'Dockerfile'
    volumes:
      - './data:/root/data'
      - './src:/root/src'
      - './out:/root/out'
    environment:
      - WRADLIB_DATA=/root/data
